linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - funlen
    - gocognit
    - wsl
    - gomnd

    - gofumpt
    - gci

    - noctx

    - nlreturn

    # TODO
    - unused
    - deadcode

linters-settings:
  # too see which are enabled: GL_DEBUG=gocritic golangci-lint run
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
    disabled-checks:
      # TODO
      - commentedOutCode
