name: Build (and deploy)

on:
  push:
    branches:
      master
  # run a minute past midnight (UTC), every day
  schedule:
    - cron: '01 00 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: Build
        run: |
          make build
          ./fruktsam
          mv dist dist_
          mkdir dist
          mv dist_ dist/historik
        env:
          FRUKTKARTAN_DATABASEURI: ${{ secrets.FRUKTKARTAN_DATABASEURI }}

  deploy:
    runs-on: ubuntu-20.04
    if: (github.event_name == 'schedule') || (github.event_name == 'workflow_dispatch')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: true
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: Build
        run: |
          make build
          ./fruktsam
          mv dist dist_
          mkdir dist
          mv dist_ dist/historik
        env:
          FRUKTKARTAN_DATABASEURI: ${{ secrets.FRUKTKARTAN_DATABASEURI }}

      - name: Cache
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update reversecache"
          branch: master
          file_pattern: reversecache
          commit_user_name: 'fruktrobot'
          commit_user_email: '<>'
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.PAGES_DEPLOY_KEY }}
          external_repository: fruktkartan/fruktkartan.github.io
          publish_branch: master
          publish_dir: ./dist
          keep_files: true
          allow_empty_commit: true
          user_name: 'fruktrobot'
          user_email: '<>'
