name: Build

on:
  push:
    branches-ignore:
      - production
  pull_request:
    branches-ignore:
      - production

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/setup-go@v2
        with:
          persist-credentials: false
          go-version: '^1.15'

      - name: Build
        run: |
          make build
