name: Deploy

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  production:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15'

      - name: Build
        run: |
          make build
          ./fruktsam

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.PAGES_DEPLOY_KEY }}
          external_repository: fruktkartan/fruktkartan.github.io
          publish_branch: master
          publish_dir: ./dist
          keep_files: true
          destination_dir: historik
          allow_empty_commit: true
          user_name: 'fruktrobot'
          user_email: '<>'
